#ifndef CONFIG_H
#define CONFIG_H

#define NUM_AREAS 2

#define GPIO_SDA 21
#define GPIO_SCL 22
#define GPIO_BUZZER 33

#define GPIO_RELAY_PUMP1 17
#define GPIO_ULTRASONIC1_TRIG 27
#define GPIO_ULTRASONIC1_ECHO 14

#define GPIO_RELAY_PUMP2 16
#define GPIO_ULTRASONIC2_TRIG 26
#define GPIO_ULTRASONIC2_ECHO 25

#define I2C_ADDR_LCD 0x27
#define LCD_COLS 16
#define LCD_ROWS 2

#define RESERVOIR_FULL_MM 20
#define RESERVOIR_EMPTY_MM 60
#define WATER_LEVEL_MIN_ALERT 25

#define ULTRASONIC_MAX_DISTANCE_CM 200
#define ULTRASONIC_NUM_READINGS 5

#define SOIL_DRY_VALUE 3600
#define SOIL_WET_VALUE 1900
#define SOIL_DRY_PERCENT 40
#define SOIL_WET_PERCENT 70

#define BUZZER_BEEP_MS 50
#define HIST_SAMPLE_INTERVAL_MS 500
#define HISTORY_SIZE 150

#define ESPNOW_CHANNEL 1
#define ESPNOW_SENSOR_TIMEOUT_MS 10000

#define WIFI_SSID "Esp32T"
#define WIFI_PASS "esp323456"
#define WIFI_AP_SSID "ROBOCORE FARM"
#define WIFI_AP_PASS "12345678"
#define WIFI_TIMEOUT_MS 20000

#define WIFI_AP_CHANNEL ESPNOW_CHANNEL

#define WEB_SERVER_PORT 80
#define SERIAL_BAUD_RATE 115200

#endif
